/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_ebox/msg/EBOXPWM.msg */
#ifndef SOEM_EBOX_BOOST_SERIALIZATION_EBOXPWM_H
#define SOEM_EBOX_BOOST_SERIALIZATION_EBOXPWM_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <soem_ebox/EBOXPWM.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_ebox::EBOXPWM_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("pwm",m.pwm);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_EBOX_BOOST_SERIALIZATION_EBOXPWM_H

