// Generated by gencpp from file soem_ebox/EBOXAnalog.msg
// DO NOT EDIT!


#ifndef SOEM_EBOX_MESSAGE_EBOXANALOG_H
#define SOEM_EBOX_MESSAGE_EBOXANALOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_ebox
{
template <class ContainerAllocator>
struct EBOXAnalog_
{
  typedef EBOXAnalog_<ContainerAllocator> Type;

  EBOXAnalog_()
    : analog()  {
      analog.assign(0.0);
  }
  EBOXAnalog_(const ContainerAllocator& _alloc)
    : analog()  {
  (void)_alloc;
      analog.assign(0.0);
  }



   typedef boost::array<float, 2>  _analog_type;
  _analog_type analog;





  typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog_<ContainerAllocator> const> ConstPtr;

}; // struct EBOXAnalog_

typedef ::soem_ebox::EBOXAnalog_<std::allocator<void> > EBOXAnalog;

typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog > EBOXAnalogPtr;
typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog const> EBOXAnalogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_ebox::EBOXAnalog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_ebox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_ebox': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_ebox/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXAnalog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXAnalog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXAnalog_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da0d2d69b62902fa94381342826fb037";
  }

  static const char* value(const ::soem_ebox::EBOXAnalog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda0d2d69b62902faULL;
  static const uint64_t static_value2 = 0x94381342826fb037ULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_ebox/EBOXAnalog";
  }

  static const char* value(const ::soem_ebox::EBOXAnalog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[2] analog\n\
";
  }

  static const char* value(const ::soem_ebox::EBOXAnalog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.analog);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EBOXAnalog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_ebox::EBOXAnalog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_ebox::EBOXAnalog_<ContainerAllocator>& v)
  {
    s << indent << "analog[]" << std::endl;
    for (size_t i = 0; i < v.analog.size(); ++i)
    {
      s << indent << "  analog[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.analog[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_EBOX_MESSAGE_EBOXANALOG_H
