// Generated by gencpp from file soem_ebox/EBOXDigital.msg
// DO NOT EDIT!


#ifndef SOEM_EBOX_MESSAGE_EBOXDIGITAL_H
#define SOEM_EBOX_MESSAGE_EBOXDIGITAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_ebox
{
template <class ContainerAllocator>
struct EBOXDigital_
{
  typedef EBOXDigital_<ContainerAllocator> Type;

  EBOXDigital_()
    : digital()  {
      digital.assign(false);
  }
  EBOXDigital_(const ContainerAllocator& _alloc)
    : digital()  {
  (void)_alloc;
      digital.assign(false);
  }



   typedef boost::array<uint8_t, 8>  _digital_type;
  _digital_type digital;





  typedef boost::shared_ptr< ::soem_ebox::EBOXDigital_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_ebox::EBOXDigital_<ContainerAllocator> const> ConstPtr;

}; // struct EBOXDigital_

typedef ::soem_ebox::EBOXDigital_<std::allocator<void> > EBOXDigital;

typedef boost::shared_ptr< ::soem_ebox::EBOXDigital > EBOXDigitalPtr;
typedef boost::shared_ptr< ::soem_ebox::EBOXDigital const> EBOXDigitalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_ebox::EBOXDigital_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_ebox::EBOXDigital_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_ebox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_ebox': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_ebox/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXDigital_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXDigital_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXDigital_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aec3537187e55892c1c92ecc0b9bccdf";
  }

  static const char* value(const ::soem_ebox::EBOXDigital_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaec3537187e55892ULL;
  static const uint64_t static_value2 = 0xc1c92ecc0b9bccdfULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_ebox/EBOXDigital";
  }

  static const char* value(const ::soem_ebox::EBOXDigital_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[8] digital\n\
";
  }

  static const char* value(const ::soem_ebox::EBOXDigital_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digital);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EBOXDigital_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_ebox::EBOXDigital_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_ebox::EBOXDigital_<ContainerAllocator>& v)
  {
    s << indent << "digital[]" << std::endl;
    for (size_t i = 0; i < v.digital.size(); ++i)
    {
      s << indent << "  digital[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.digital[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_EBOX_MESSAGE_EBOXDIGITAL_H
