// Generated by gencpp from file soem_ebox/EBOXPWM.msg
// DO NOT EDIT!


#ifndef SOEM_EBOX_MESSAGE_EBOXPWM_H
#define SOEM_EBOX_MESSAGE_EBOXPWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_ebox
{
template <class ContainerAllocator>
struct EBOXPWM_
{
  typedef EBOXPWM_<ContainerAllocator> Type;

  EBOXPWM_()
    : pwm()  {
      pwm.assign(0.0);
  }
  EBOXPWM_(const ContainerAllocator& _alloc)
    : pwm()  {
  (void)_alloc;
      pwm.assign(0.0);
  }



   typedef boost::array<float, 2>  _pwm_type;
  _pwm_type pwm;





  typedef boost::shared_ptr< ::soem_ebox::EBOXPWM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_ebox::EBOXPWM_<ContainerAllocator> const> ConstPtr;

}; // struct EBOXPWM_

typedef ::soem_ebox::EBOXPWM_<std::allocator<void> > EBOXPWM;

typedef boost::shared_ptr< ::soem_ebox::EBOXPWM > EBOXPWMPtr;
typedef boost::shared_ptr< ::soem_ebox::EBOXPWM const> EBOXPWMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_ebox::EBOXPWM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_ebox::EBOXPWM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_ebox

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_ebox': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_ebox/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_ebox::EBOXPWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_ebox::EBOXPWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_ebox::EBOXPWM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d644c5720c3d45355d4cb6a20aa7362";
  }

  static const char* value(const ::soem_ebox::EBOXPWM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d644c5720c3d453ULL;
  static const uint64_t static_value2 = 0x55d4cb6a20aa7362ULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_ebox/EBOXPWM";
  }

  static const char* value(const ::soem_ebox::EBOXPWM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[2] pwm\n\
";
  }

  static const char* value(const ::soem_ebox::EBOXPWM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EBOXPWM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_ebox::EBOXPWM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_ebox::EBOXPWM_<ContainerAllocator>& v)
  {
    s << indent << "pwm[]" << std::endl;
    for (size_t i = 0; i < v.pwm.size(); ++i)
    {
      s << indent << "  pwm[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pwm[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_EBOX_MESSAGE_EBOXPWM_H
