// Generated by gencpp from file motion_control_msgs/JointVelocities.msg
// DO NOT EDIT!


#ifndef MOTION_CONTROL_MSGS_MESSAGE_JOINTVELOCITIES_H
#define MOTION_CONTROL_MSGS_MESSAGE_JOINTVELOCITIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_control_msgs
{
template <class ContainerAllocator>
struct JointVelocities_
{
  typedef JointVelocities_<ContainerAllocator> Type;

  JointVelocities_()
    : names()
    , velocities()  {
    }
  JointVelocities_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , velocities(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocities_type;
  _velocities_type velocities;





  typedef boost::shared_ptr< ::motion_control_msgs::JointVelocities_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_control_msgs::JointVelocities_<ContainerAllocator> const> ConstPtr;

}; // struct JointVelocities_

typedef ::motion_control_msgs::JointVelocities_<std::allocator<void> > JointVelocities;

typedef boost::shared_ptr< ::motion_control_msgs::JointVelocities > JointVelocitiesPtr;
typedef boost::shared_ptr< ::motion_control_msgs::JointVelocities const> JointVelocitiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_control_msgs::JointVelocities_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motion_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'motion_control_msgs': ['/home/giel/etasl/ws/my_new_workspace/src/motion_control/motion_control_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_control_msgs::JointVelocities_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_control_msgs::JointVelocities_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_control_msgs::JointVelocities_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfb96d7fc4b39e1d076142cb6618c930";
  }

  static const char* value(const ::motion_control_msgs::JointVelocities_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfb96d7fc4b39e1dULL;
  static const uint64_t static_value2 = 0x076142cb6618c930ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_control_msgs/JointVelocities";
  }

  static const char* value(const ::motion_control_msgs::JointVelocities_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n\
float64[] velocities\n\
";
  }

  static const char* value(const ::motion_control_msgs::JointVelocities_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointVelocities_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_control_msgs::JointVelocities_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_control_msgs::JointVelocities_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CONTROL_MSGS_MESSAGE_JOINTVELOCITIES_H
