// Generated by gencpp from file lwr_fri_msgs/CartesianImpedance.msg
// DO NOT EDIT!


#ifndef LWR_FRI_MSGS_MESSAGE_CARTESIANIMPEDANCE_H
#define LWR_FRI_MSGS_MESSAGE_CARTESIANIMPEDANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace lwr_fri_msgs
{
template <class ContainerAllocator>
struct CartesianImpedance_
{
  typedef CartesianImpedance_<ContainerAllocator> Type;

  CartesianImpedance_()
    : stiffness()
    , damping()  {
    }
  CartesianImpedance_(const ContainerAllocator& _alloc)
    : stiffness(_alloc)
    , damping(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _stiffness_type;
  _stiffness_type stiffness;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _damping_type;
  _damping_type damping;





  typedef boost::shared_ptr< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianImpedance_

typedef ::lwr_fri_msgs::CartesianImpedance_<std::allocator<void> > CartesianImpedance;

typedef boost::shared_ptr< ::lwr_fri_msgs::CartesianImpedance > CartesianImpedancePtr;
typedef boost::shared_ptr< ::lwr_fri_msgs::CartesianImpedance const> CartesianImpedanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lwr_fri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lwr_fri_msgs': ['/home/giel/etasl/ws/my_new_workspace/src/kuka-robot-hardware/lwr_fri_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd4dbca8475cfa8e858db7599bb64f48";
  }

  static const char* value(const ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd4dbca8475cfa8eULL;
  static const uint64_t static_value2 = 0x858db7599bb64f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lwr_fri_msgs/CartesianImpedance";
  }

  static const char* value(const ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist stiffness\n\
geometry_msgs/Twist damping\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stiffness);
      stream.next(m.damping);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianImpedance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lwr_fri_msgs::CartesianImpedance_<ContainerAllocator>& v)
  {
    s << indent << "stiffness: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.stiffness);
    s << indent << "damping: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.damping);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LWR_FRI_MSGS_MESSAGE_CARTESIANIMPEDANCE_H
