// Generated by gencpp from file lwr_fri_msgs/FriJointImpedance.msg
// DO NOT EDIT!


#ifndef LWR_FRI_MSGS_MESSAGE_FRIJOINTIMPEDANCE_H
#define LWR_FRI_MSGS_MESSAGE_FRIJOINTIMPEDANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lwr_fri_msgs
{
template <class ContainerAllocator>
struct FriJointImpedance_
{
  typedef FriJointImpedance_<ContainerAllocator> Type;

  FriJointImpedance_()
    : stiffness()
    , damping()  {
      stiffness.assign(0.0);

      damping.assign(0.0);
  }
  FriJointImpedance_(const ContainerAllocator& _alloc)
    : stiffness()
    , damping()  {
  (void)_alloc;
      stiffness.assign(0.0);

      damping.assign(0.0);
  }



   typedef boost::array<float, 7>  _stiffness_type;
  _stiffness_type stiffness;

   typedef boost::array<float, 7>  _damping_type;
  _damping_type damping;





  typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> const> ConstPtr;

}; // struct FriJointImpedance_

typedef ::lwr_fri_msgs::FriJointImpedance_<std::allocator<void> > FriJointImpedance;

typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointImpedance > FriJointImpedancePtr;
typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointImpedance const> FriJointImpedanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lwr_fri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lwr_fri_msgs': ['/home/giel/etasl/ws/my_new_workspace/src/kuka-robot-hardware/lwr_fri_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d99cffe99f4e45e313ffa6bb7c0de4e";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d99cffe99f4e45eULL;
  static const uint64_t static_value2 = 0x313ffa6bb7c0de4eULL;
};

template<class ContainerAllocator>
struct DataType< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lwr_fri_msgs/FriJointImpedance";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[7] stiffness\n\
float32[7] damping\n\
";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stiffness);
      stream.next(m.damping);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FriJointImpedance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator>& v)
  {
    s << indent << "stiffness[]" << std::endl;
    for (size_t i = 0; i < v.stiffness.size(); ++i)
    {
      s << indent << "  stiffness[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.stiffness[i]);
    }
    s << indent << "damping[]" << std::endl;
    for (size_t i = 0; i < v.damping.size(); ++i)
    {
      s << indent << "  damping[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.damping[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LWR_FRI_MSGS_MESSAGE_FRIJOINTIMPEDANCE_H
