// Generated by gencpp from file lwr_fri_msgs/FriJointState.msg
// DO NOT EDIT!


#ifndef LWR_FRI_MSGS_MESSAGE_FRIJOINTSTATE_H
#define LWR_FRI_MSGS_MESSAGE_FRIJOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lwr_fri_msgs
{
template <class ContainerAllocator>
struct FriJointState_
{
  typedef FriJointState_<ContainerAllocator> Type;

  FriJointState_()
    : header()
    , msrJntPos()
    , cmdJntPos()
    , cmdJntPosFriOffset()
    , msrJntTrq()
    , estExtJntTrq()
    , gravity()  {
      msrJntPos.assign(0.0);

      cmdJntPos.assign(0.0);

      cmdJntPosFriOffset.assign(0.0);

      msrJntTrq.assign(0.0);

      estExtJntTrq.assign(0.0);

      gravity.assign(0.0);
  }
  FriJointState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , msrJntPos()
    , cmdJntPos()
    , cmdJntPosFriOffset()
    , msrJntTrq()
    , estExtJntTrq()
    , gravity()  {
  (void)_alloc;
      msrJntPos.assign(0.0);

      cmdJntPos.assign(0.0);

      cmdJntPosFriOffset.assign(0.0);

      msrJntTrq.assign(0.0);

      estExtJntTrq.assign(0.0);

      gravity.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 7>  _msrJntPos_type;
  _msrJntPos_type msrJntPos;

   typedef boost::array<float, 7>  _cmdJntPos_type;
  _cmdJntPos_type cmdJntPos;

   typedef boost::array<float, 7>  _cmdJntPosFriOffset_type;
  _cmdJntPosFriOffset_type cmdJntPosFriOffset;

   typedef boost::array<float, 7>  _msrJntTrq_type;
  _msrJntTrq_type msrJntTrq;

   typedef boost::array<float, 7>  _estExtJntTrq_type;
  _estExtJntTrq_type estExtJntTrq;

   typedef boost::array<float, 7>  _gravity_type;
  _gravity_type gravity;





  typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> const> ConstPtr;

}; // struct FriJointState_

typedef ::lwr_fri_msgs::FriJointState_<std::allocator<void> > FriJointState;

typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointState > FriJointStatePtr;
typedef boost::shared_ptr< ::lwr_fri_msgs::FriJointState const> FriJointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lwr_fri_msgs::FriJointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lwr_fri_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lwr_fri_msgs': ['/home/giel/etasl/ws/my_new_workspace/src/kuka-robot-hardware/lwr_fri_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b96281d768d86477f17b62daa820d6d";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b96281d768d8647ULL;
  static const uint64_t static_value2 = 0x7f17b62daa820d6dULL;
};

template<class ContainerAllocator>
struct DataType< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lwr_fri_msgs/FriJointState";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[7] msrJntPos\n\
float32[7] cmdJntPos\n\
float32[7] cmdJntPosFriOffset\n\
float32[7] msrJntTrq\n\
float32[7] estExtJntTrq\n\
float32[7] gravity\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lwr_fri_msgs::FriJointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.msrJntPos);
      stream.next(m.cmdJntPos);
      stream.next(m.cmdJntPosFriOffset);
      stream.next(m.msrJntTrq);
      stream.next(m.estExtJntTrq);
      stream.next(m.gravity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FriJointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lwr_fri_msgs::FriJointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lwr_fri_msgs::FriJointState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "msrJntPos[]" << std::endl;
    for (size_t i = 0; i < v.msrJntPos.size(); ++i)
    {
      s << indent << "  msrJntPos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.msrJntPos[i]);
    }
    s << indent << "cmdJntPos[]" << std::endl;
    for (size_t i = 0; i < v.cmdJntPos.size(); ++i)
    {
      s << indent << "  cmdJntPos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cmdJntPos[i]);
    }
    s << indent << "cmdJntPosFriOffset[]" << std::endl;
    for (size_t i = 0; i < v.cmdJntPosFriOffset.size(); ++i)
    {
      s << indent << "  cmdJntPosFriOffset[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cmdJntPosFriOffset[i]);
    }
    s << indent << "msrJntTrq[]" << std::endl;
    for (size_t i = 0; i < v.msrJntTrq.size(); ++i)
    {
      s << indent << "  msrJntTrq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.msrJntTrq[i]);
    }
    s << indent << "estExtJntTrq[]" << std::endl;
    for (size_t i = 0; i < v.estExtJntTrq.size(); ++i)
    {
      s << indent << "  estExtJntTrq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.estExtJntTrq[i]);
    }
    s << indent << "gravity[]" << std::endl;
    for (size_t i = 0; i < v.gravity.size(); ++i)
    {
      s << indent << "  gravity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gravity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LWR_FRI_MSGS_MESSAGE_FRIJOINTSTATE_H
