// Generated by gencpp from file soem_beckhoff_drivers/CommMsg.msg
// DO NOT EDIT!


#ifndef SOEM_BECKHOFF_DRIVERS_MESSAGE_COMMMSG_H
#define SOEM_BECKHOFF_DRIVERS_MESSAGE_COMMMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_beckhoff_drivers
{
template <class ContainerAllocator>
struct CommMsg_
{
  typedef CommMsg_<ContainerAllocator> Type;

  CommMsg_()
    : datapacket()
    , datasize(0)  {
    }
  CommMsg_(const ContainerAllocator& _alloc)
    : datapacket(_alloc)
    , datasize(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _datapacket_type;
  _datapacket_type datapacket;

   typedef uint8_t _datasize_type;
  _datasize_type datasize;





  typedef boost::shared_ptr< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CommMsg_

typedef ::soem_beckhoff_drivers::CommMsg_<std::allocator<void> > CommMsg;

typedef boost::shared_ptr< ::soem_beckhoff_drivers::CommMsg > CommMsgPtr;
typedef boost::shared_ptr< ::soem_beckhoff_drivers::CommMsg const> CommMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_beckhoff_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'soem_beckhoff_drivers': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8312abb0799e3ce28f5c343af99bc5eb";
  }

  static const char* value(const ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8312abb0799e3ce2ULL;
  static const uint64_t static_value2 = 0x8f5c343af99bc5ebULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_beckhoff_drivers/CommMsg";
  }

  static const char* value(const ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] datapacket\n\
uint8 datasize\n\
";
  }

  static const char* value(const ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.datapacket);
      stream.next(m.datasize);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_beckhoff_drivers::CommMsg_<ContainerAllocator>& v)
  {
    s << indent << "datapacket[]" << std::endl;
    for (size_t i = 0; i < v.datapacket.size(); ++i)
    {
      s << indent << "  datapacket[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.datapacket[i]);
    }
    s << indent << "datasize: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.datasize);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_BECKHOFF_DRIVERS_MESSAGE_COMMMSG_H
