// Generated by gencpp from file soem_beckhoff_drivers/EncoderOutMsg.msg
// DO NOT EDIT!


#ifndef SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODEROUTMSG_H
#define SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODEROUTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_beckhoff_drivers
{
template <class ContainerAllocator>
struct EncoderOutMsg_
{
  typedef EncoderOutMsg_<ContainerAllocator> Type;

  EncoderOutMsg_()
    : control(0)
    , outvalue(0)  {
    }
  EncoderOutMsg_(const ContainerAllocator& _alloc)
    : control(0)
    , outvalue(0)  {
  (void)_alloc;
    }



   typedef uint8_t _control_type;
  _control_type control;

   typedef uint16_t _outvalue_type;
  _outvalue_type outvalue;





  typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderOutMsg_

typedef ::soem_beckhoff_drivers::EncoderOutMsg_<std::allocator<void> > EncoderOutMsg;

typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderOutMsg > EncoderOutMsgPtr;
typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderOutMsg const> EncoderOutMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_beckhoff_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_beckhoff_drivers': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "297826ed745b96cde20150fa2f0950c2";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x297826ed745b96cdULL;
  static const uint64_t static_value2 = 0xe20150fa2f0950c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_beckhoff_drivers/EncoderOutMsg";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 control\n\
uint16 outvalue\n\
";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control);
      stream.next(m.outvalue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderOutMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator>& v)
  {
    s << indent << "control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control);
    s << indent << "outvalue: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.outvalue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODEROUTMSG_H
