// Generated by gencpp from file soem_beckhoff_drivers/EncoderMsg.msg
// DO NOT EDIT!


#ifndef SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODERMSG_H
#define SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODERMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_beckhoff_drivers
{
template <class ContainerAllocator>
struct EncoderMsg_
{
  typedef EncoderMsg_<ContainerAllocator> Type;

  EncoderMsg_()
    : value(0)  {
    }
  EncoderMsg_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint16_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderMsg_

typedef ::soem_beckhoff_drivers::EncoderMsg_<std::allocator<void> > EncoderMsg;

typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderMsg > EncoderMsgPtr;
typedef boost::shared_ptr< ::soem_beckhoff_drivers::EncoderMsg const> EncoderMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_beckhoff_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_beckhoff_drivers': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e68bf91459258a84dab807f5c768df7";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e68bf91459258a8ULL;
  static const uint64_t static_value2 = 0x4dab807f5c768df7ULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_beckhoff_drivers/EncoderMsg";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 value\n\
";
  }

  static const char* value(const ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_beckhoff_drivers::EncoderMsg_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_BECKHOFF_DRIVERS_MESSAGE_ENCODERMSG_H
