// Generated by gencpp from file soem_beckhoff_drivers/PSUMsg.msg
// DO NOT EDIT!


#ifndef SOEM_BECKHOFF_DRIVERS_MESSAGE_PSUMSG_H
#define SOEM_BECKHOFF_DRIVERS_MESSAGE_PSUMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace soem_beckhoff_drivers
{
template <class ContainerAllocator>
struct PSUMsg_
{
  typedef PSUMsg_<ContainerAllocator> Type;

  PSUMsg_()
    : power_ok(false)
    , overload(false)  {
    }
  PSUMsg_(const ContainerAllocator& _alloc)
    : power_ok(false)
    , overload(false)  {
  (void)_alloc;
    }



   typedef uint8_t _power_ok_type;
  _power_ok_type power_ok;

   typedef uint8_t _overload_type;
  _overload_type overload;





  typedef boost::shared_ptr< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> const> ConstPtr;

}; // struct PSUMsg_

typedef ::soem_beckhoff_drivers::PSUMsg_<std::allocator<void> > PSUMsg;

typedef boost::shared_ptr< ::soem_beckhoff_drivers::PSUMsg > PSUMsgPtr;
typedef boost::shared_ptr< ::soem_beckhoff_drivers::PSUMsg const> PSUMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace soem_beckhoff_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'soem_beckhoff_drivers': ['/home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d640ba06d2b65ae841e25741b04ea2c";
  }

  static const char* value(const ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d640ba06d2b65aeULL;
  static const uint64_t static_value2 = 0x841e25741b04ea2cULL;
};

template<class ContainerAllocator>
struct DataType< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "soem_beckhoff_drivers/PSUMsg";
  }

  static const char* value(const ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool power_ok\n\
bool overload\n\
";
  }

  static const char* value(const ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power_ok);
      stream.next(m.overload);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PSUMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator>& v)
  {
    s << indent << "power_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power_ok);
    s << indent << "overload: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overload);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOEM_BECKHOFF_DRIVERS_MESSAGE_PSUMSG_H
