/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg/AnalogMsg.msg */
#ifndef SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ANALOGMSG_H
#define SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ANALOGMSG_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <soem_beckhoff_drivers/AnalogMsg.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_beckhoff_drivers::AnalogMsg_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("values",m.values);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ANALOGMSG_H

