/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg/CommMsgBig.msg */
#ifndef SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_COMMMSGBIG_H
#define SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_COMMMSGBIG_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <soem_beckhoff_drivers/CommMsgBig.h>
#include <soem_beckhoff_drivers/boost/CommMsg.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_beckhoff_drivers::CommMsgBig_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("channels",m.channels);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_COMMMSGBIG_H

