/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg/EncoderOutMsg.msg */
#ifndef SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ENCODEROUTMSG_H
#define SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ENCODEROUTMSG_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <soem_beckhoff_drivers/EncoderOutMsg.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_beckhoff_drivers::EncoderOutMsg_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("control",m.control);
    a & make_nvp("outvalue",m.outvalue);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_ENCODEROUTMSG_H

