/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/rtt_soem/soem_beckhoff_drivers/msg/PSUMsg.msg */
#ifndef SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_PSUMSG_H
#define SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_PSUMSG_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <soem_beckhoff_drivers/PSUMsg.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_beckhoff_drivers::PSUMsg_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("power_ok",m.power_ok);
    a & make_nvp("overload",m.overload);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_BECKHOFF_DRIVERS_BOOST_SERIALIZATION_PSUMSG_H

