# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_fri_msgs/CartesianImpedance.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CartesianImpedance(genpy.Message):
  _md5sum = "bd4dbca8475cfa8e858db7599bb64f48"
  _type = "lwr_fri_msgs/CartesianImpedance"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Twist stiffness
geometry_msgs/Twist damping
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['stiffness','damping']
  _slot_types = ['geometry_msgs/Twist','geometry_msgs/Twist']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stiffness,damping

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CartesianImpedance, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stiffness is None:
        self.stiffness = geometry_msgs.msg.Twist()
      if self.damping is None:
        self.damping = geometry_msgs.msg.Twist()
    else:
      self.stiffness = geometry_msgs.msg.Twist()
      self.damping = geometry_msgs.msg.Twist()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.stiffness.linear.x, _x.stiffness.linear.y, _x.stiffness.linear.z, _x.stiffness.angular.x, _x.stiffness.angular.y, _x.stiffness.angular.z, _x.damping.linear.x, _x.damping.linear.y, _x.damping.linear.z, _x.damping.angular.x, _x.damping.angular.y, _x.damping.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stiffness is None:
        self.stiffness = geometry_msgs.msg.Twist()
      if self.damping is None:
        self.damping = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.stiffness.linear.x, _x.stiffness.linear.y, _x.stiffness.linear.z, _x.stiffness.angular.x, _x.stiffness.angular.y, _x.stiffness.angular.z, _x.damping.linear.x, _x.damping.linear.y, _x.damping.linear.z, _x.damping.angular.x, _x.damping.angular.y, _x.damping.angular.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.stiffness.linear.x, _x.stiffness.linear.y, _x.stiffness.linear.z, _x.stiffness.angular.x, _x.stiffness.angular.y, _x.stiffness.angular.z, _x.damping.linear.x, _x.damping.linear.y, _x.damping.linear.z, _x.damping.angular.x, _x.damping.angular.y, _x.damping.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stiffness is None:
        self.stiffness = geometry_msgs.msg.Twist()
      if self.damping is None:
        self.damping = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.stiffness.linear.x, _x.stiffness.linear.y, _x.stiffness.linear.z, _x.stiffness.angular.x, _x.stiffness.angular.y, _x.stiffness.angular.z, _x.damping.linear.x, _x.damping.linear.y, _x.damping.linear.z, _x.damping.angular.x, _x.damping.angular.y, _x.damping.angular.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
