# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_fri_msgs/FriRobotJntData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FriRobotJntData(genpy.Message):
  _md5sum = "0aaff558814188d51a3ef7a1023d53a7"
  _type = "lwr_fri_msgs/FriRobotJntData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[7] msrJntPos
float32[7] cmdJntPos
float32[7] cmdJntPosFriOffset
float32[7] msrJntTrq
float32[7] estExtJntTrq
float32[7] gravity"""
  __slots__ = ['msrJntPos','cmdJntPos','cmdJntPosFriOffset','msrJntTrq','estExtJntTrq','gravity']
  _slot_types = ['float32[7]','float32[7]','float32[7]','float32[7]','float32[7]','float32[7]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msrJntPos,cmdJntPos,cmdJntPosFriOffset,msrJntTrq,estExtJntTrq,gravity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FriRobotJntData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.msrJntPos is None:
        self.msrJntPos = [0.] * 7
      if self.cmdJntPos is None:
        self.cmdJntPos = [0.] * 7
      if self.cmdJntPosFriOffset is None:
        self.cmdJntPosFriOffset = [0.] * 7
      if self.msrJntTrq is None:
        self.msrJntTrq = [0.] * 7
      if self.estExtJntTrq is None:
        self.estExtJntTrq = [0.] * 7
      if self.gravity is None:
        self.gravity = [0.] * 7
    else:
      self.msrJntPos = [0.] * 7
      self.cmdJntPos = [0.] * 7
      self.cmdJntPosFriOffset = [0.] * 7
      self.msrJntTrq = [0.] * 7
      self.estExtJntTrq = [0.] * 7
      self.gravity = [0.] * 7

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_7f().pack(*self.msrJntPos))
      buff.write(_get_struct_7f().pack(*self.cmdJntPos))
      buff.write(_get_struct_7f().pack(*self.cmdJntPosFriOffset))
      buff.write(_get_struct_7f().pack(*self.msrJntTrq))
      buff.write(_get_struct_7f().pack(*self.estExtJntTrq))
      buff.write(_get_struct_7f().pack(*self.gravity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 28
      self.msrJntPos = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.cmdJntPos = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.cmdJntPosFriOffset = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.msrJntTrq = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.estExtJntTrq = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.gravity = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.msrJntPos.tostring())
      buff.write(self.cmdJntPos.tostring())
      buff.write(self.cmdJntPosFriOffset.tostring())
      buff.write(self.msrJntTrq.tostring())
      buff.write(self.estExtJntTrq.tostring())
      buff.write(self.gravity.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 28
      self.msrJntPos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.cmdJntPos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.cmdJntPosFriOffset = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.msrJntTrq = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.estExtJntTrq = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.gravity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
