# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lwr_fri_msgs/FriJointState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class FriJointState(genpy.Message):
  _md5sum = "9b96281d768d86477f17b62daa820d6d"
  _type = "lwr_fri_msgs/FriJointState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float32[7] msrJntPos
float32[7] cmdJntPos
float32[7] cmdJntPosFriOffset
float32[7] msrJntTrq
float32[7] estExtJntTrq
float32[7] gravity
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','msrJntPos','cmdJntPos','cmdJntPosFriOffset','msrJntTrq','estExtJntTrq','gravity']
  _slot_types = ['std_msgs/Header','float32[7]','float32[7]','float32[7]','float32[7]','float32[7]','float32[7]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,msrJntPos,cmdJntPos,cmdJntPosFriOffset,msrJntTrq,estExtJntTrq,gravity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FriJointState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.msrJntPos is None:
        self.msrJntPos = [0.] * 7
      if self.cmdJntPos is None:
        self.cmdJntPos = [0.] * 7
      if self.cmdJntPosFriOffset is None:
        self.cmdJntPosFriOffset = [0.] * 7
      if self.msrJntTrq is None:
        self.msrJntTrq = [0.] * 7
      if self.estExtJntTrq is None:
        self.estExtJntTrq = [0.] * 7
      if self.gravity is None:
        self.gravity = [0.] * 7
    else:
      self.header = std_msgs.msg.Header()
      self.msrJntPos = [0.] * 7
      self.cmdJntPos = [0.] * 7
      self.cmdJntPosFriOffset = [0.] * 7
      self.msrJntTrq = [0.] * 7
      self.estExtJntTrq = [0.] * 7
      self.gravity = [0.] * 7

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_7f().pack(*self.msrJntPos))
      buff.write(_get_struct_7f().pack(*self.cmdJntPos))
      buff.write(_get_struct_7f().pack(*self.cmdJntPosFriOffset))
      buff.write(_get_struct_7f().pack(*self.msrJntTrq))
      buff.write(_get_struct_7f().pack(*self.estExtJntTrq))
      buff.write(_get_struct_7f().pack(*self.gravity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 28
      self.msrJntPos = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.cmdJntPos = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.cmdJntPosFriOffset = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.msrJntTrq = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.estExtJntTrq = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 28
      self.gravity = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.msrJntPos.tostring())
      buff.write(self.cmdJntPos.tostring())
      buff.write(self.cmdJntPosFriOffset.tostring())
      buff.write(self.msrJntTrq.tostring())
      buff.write(self.estExtJntTrq.tostring())
      buff.write(self.gravity.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 28
      self.msrJntPos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.cmdJntPos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.cmdJntPosFriOffset = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.msrJntTrq = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.estExtJntTrq = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      start = end
      end += 28
      self.gravity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
