/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/kuka-robot-hardware/lwr_fri_msgs/msg/FriJointImpedance.msg */
#ifndef LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIJOINTIMPEDANCE_H
#define LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIJOINTIMPEDANCE_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <lwr_fri_msgs/FriJointImpedance.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::lwr_fri_msgs::FriJointImpedance_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("stiffness",m.stiffness);
    a & make_nvp("damping",m.damping);
}

} // namespace serialization
} // namespace boost

#endif // LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIJOINTIMPEDANCE_H

