/* Auto-generated by create_boost_header.py for file /home/giel/etasl/ws/my_new_workspace/src/kuka-robot-hardware/lwr_fri_msgs/msg/FriRobotData.msg */
#ifndef LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIROBOTDATA_H
#define LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIROBOTDATA_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <lwr_fri_msgs/FriRobotData.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::lwr_fri_msgs::FriRobotData_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("msrJntPos",m.msrJntPos);
    a & make_nvp("cmdJntPos",m.cmdJntPos);
    a & make_nvp("cmdJntPosFriOffset",m.cmdJntPosFriOffset);
}

} // namespace serialization
} // namespace boost

#endif // LWR_FRI_MSGS_BOOST_SERIALIZATION_FRIROBOTDATA_H

